* <2015-08-04 Tue>
** Discussion
   What kind of system grows without bound? I.e: has positive
   feedback?
   - Wildfire
   - Corruption in government
   - Population without predators
   - Greenhouse effect
** Work
   Come up with at least 3 ideas that can change the global
   environment drastically that we can implement in daisy world.
   - Meteor strike
   - Volcano
   - Fire
   - Greenhouse effect
** Independent ideas
   - Daisy predators?
     - Goes against the whole idea of planet only occupied by daisies
   - "Harvesters"
     - Where daisies are harvested from a certain area, periodically
       killing them off
   - Different maximum age for different daisies
     - I.e: black lives longer than white?
   - Different growth rates at different temperatures?
     - Attempt to knock the balance off-kilter
     - White prefers high temps and black low temps (Might actually
       cause oscillation, would be interesting...)
     - White prefers low temps and black high temps, essentially
       positive feedback.

   http://www.uwa.edu.au/__data/assets/pdf_file/0006/1637367/Wittwer_2005.pdf
* <2015-08-18 Tue>
** Draft abstract
   Points to make:
   - What:
     - What problem are we trying to solve?
     - What were the results of your research?
     - What are the implications of the research?
   - Why:
     - Why are we doing this?
   - How:
     - How are we going to do this?
     - How are we going to change it from previous research?

   Daisyworld is a computer simulation proposed by James Lovelock and
   Andrew Watson in a paper published in 1983. It proposes the
   possibility of a simple system that self regulates via the albedo
   of the two kinds of daisies that grow on an isolated planet. In
   an attempt to illustrate the effects of speciation(?), the computer
   simulation is modified by having the two types of daisies flourish
   at different temperatures. This modification induced (X) and
   showed (Y). Etc?
** Program design
   - World
     - Contains some topology of the entire planet, make it simple
       and be a grid/torus
     - Each tile contains either a type of daisy or bare earth
     - Manages the temperatures at each of the tiles using the
       incident radiation and the amount absorbed by the albedo at
       each tile
   - Tile
     - Contains a daisy or bare earth
     - Has a incident amount of light
     - Has an albedo, dependent on the object at this tile
     - Has a local temperature, local object is dependent on this
     - Does it need a number of time steps since the "object" has
       been living on it?
       - I.e: the daisy will be more likely to die dependent on the
	 difference between the ideal temp and the local temp as well
	 as the amount of time since it spawned
     - At each time step, this has to calculate the probability of
       certain events happening, e.g: the daisy dying or a new daisy
       spawning
       - Will we have multiple daisies in one tile?
   - Daisy
     - Can spawn, grow, die
     - Growth is dependent on the incident radiation and temperature
       (delta ideal temp)
     - Has an albedo (independent from the containing tile)
     - Has an ideal temperature (template programming or just an
       overloaded constructor?)
     - "Just a container" to be handled by the containing tile
     - Has an ideal spawn temperature, make this dependent on the
       type of daisy?
   - Sun
     - Has an output of radiation
     - Radiation can increase/decrease over time
     - Affects global temperature via amount of radiation
     - Controlled by user?
   - UI
     - Controlled by user
     - Should contain graphs of spawn probability vs temp for each
       type of daisy
     - Should show topology of the planet with graphics for daisies
     - Should have some kind of input for ideal daisy temp and
       incident radiation
     - Should have input for incident radiation vs time
     - Should communicate only with an eventbus(?) Callbacks
       complicate things a bit too much, makes my life easier.
   *
* <2015-08-18 Tue>
** What makes a good title?
   - Be informative
   - Be catchy
   - Can't be too long
   - Keywords
     - Often are specified in the article
     - e.g: Daisyworld, homeostatic, climate
   - Have to be unabiguouos
   - Memorable!
   - Catchphrase; explains a lot in a few words
   - Impactful words, then a sentence explaining what it is about
** What makes a bad title?
   - Uses Jargon
   - Vague
   -
** Good titles?
   - Daisyworld; the tale of two flowers



** This week
   - Start coding classes
     - Idea for UI/graphics pyQT
   - Read "Individual based modelling and ecology" by Grimm
     - Remember to mention agent-based model in paper introduction

* <2015-08-23 Sun>
** Papers
*** Self sustained temperature oscillations on daisyworld
    http://onlinelibrary.wiley.com.ezproxy.lib.monash.edu.au/doi/10.1034/j.1600-0889.1999.t01-3-00005.x/pdf

    - Seems like they try to induce the same model that I'm trying to
      do, with black and white daisies having different "optimal"
      temperatures
    - They only use the mathematical model, no actual computer
      simulation takes place...
    - Oscillations only take place when both daisies exist
    - Oscillations depend on the solar luminosity, at the extremities
      damped oscillations can take place (something to investigate...)
*** Catastrophes on daisyworld
    http://ac.els-cdn.com.ezproxy.lib.monash.edu.au/S0169534703000971/1-s2.0-S0169534703000971-main.pdf?_tid=475b389c-4985-11e5-82a3-00000aab0f27&acdnat=1440327428_a53255f04ad37eb872bca0b58949ea50
    - This is more like a description of daisyworld and how it should
      actually be written about more in ecological papers...
    - Is actually quite nice to read if somebody didn't really have an
      understanding of daisyworld, try to write like this in
      introduction?
    - Has good references to other papers and a summarisation of what
      they actually say, nice!
    - Refers to another paper where a desert grows across the world? Idea?
*** Catastrophic desert formation in daisyworld
    http://ac.els-cdn.com.ezproxy.lib.monash.edu.au/S0022519303000699/1-s2.0-S0022519303000699-main.pdf?_tid=22a7e238-4986-11e5-a18a-00000aacb35f&acdnat=1440327796_1bff9d861652a3885ef56018c69e54bf
    - Paper commented on in previous section
    - Actually has a spacial model for simulation
    - Nicely worded abstract, understandable if you already know of daisyworld
    - Desert comes about due to emulation of latitudes and the
      difference of incident solar radiation
    - Has pictures of their simulation
    - Nicely worded analysis of the critical points in the
      temperature/solar radiation curves in conclusion
* <2015-08-25 Tue>
** Code progress
   Implemented a basic implementation of daisyworld, just by
   "eyeballing" the paper. The system that I've implemented is rather
   naive and is really just an approximation of the daisyworld
   specified in the paper.
   Things to tune:
   - Probability of a daisy growing at some point
   - Daisy death vs temperature + age instead of just age
   - Different probability for growth of different types of daisies vs temperature
   - Different "optimal" points for different types of daisies
** To Read
*** Daisyworld: a review
    http://www.dpi.inpe.br/gilberto/cursos/cst-317/papers/daisyworld_review.pdf
    -
*** Self stabilization of the biosphere under global change
    :PROPERTIES:
    :ID:       aa18bb5a-b300-4293-89fa-46e2ad1a8d84
    :END:
    - a tutorial geological approach
* <2015-09-01 Tue>
  Made the text within the tile change color depending on the current temp.
  Right now it is a rather naive method, might want to fix that later.
** <2015-09-14 Mon>
   Reworked the color temp to use the Hue from 0 to 255, I.e red to dark purple.
   Now it looks fancier, a better heat map...

* <2015-09-07 Mon>
  Moving on to implementing UI now, really quite easy since I chose QT as the framework.
  Not exactly the best architecture though, with each inner stage having to keep a
  reference to their parent in order to implement some stuff, like daisies having to
  know the temp of the tile they occupy. It works, so no need to change it now.
* <2015-09-11 Fri>
  I noticed that there was way too much oscillation to classify the simulation as "homeostatic",
  I.e the temperature would deviate up to 10 degrees from the "optimal temp" of 22.5 in a system
  with only normal daisies at 1.0 luminosity.

  To fix this I made the daisies not only die depending on some factor of the difference between
  the "optimal temp" and the current temp, but I also made the daisies lifespan much shorter, from
  100 ticks to 20 ticks. Oscillation is now about ± 2.5 degrees from the optimal temp.
** TODO Implementation
   - Have to figure out a way to make all the optional daisies die based on user input
     - Idea: When checking daisies, compare them against current available types of daisies,
       if they don't exist, kill them.
* <2015-09-22 Tue>
  Introduction
  - include agent-based models, how, why, references, examples.
    - How it has been used in other research
    - Why we have decided to use one
    - Remember to add references to other research that use an agent based model
    - Add examples of how they are used

  - STRUCTURE, include a paragraph that explains how the paper is laid out
- equations, can use equation references from other papers
- how are we going to use the simulation?
